### ISSUE TITLE
Directory structure

### ISSUE THREAD

**Issue by Naphier** [RowellKataan/Unity-SQL-Server-and-Networking-DevKit#1]
If this is planned for release as a unitypackage then it would be prudent to place all of the directories in Assets into a subfolder (Assets/SQLDevKit?). That way when this package is imported it won't place scripts and other assets into existing folders. The exception to this would be the Standard Assets folder, which could remain at the root of Assets for the user to decide to import or not.

**Comment by RowellKataan** [comment]
Placed files into a project specific directory which is housed under the Assets root directory.  Standard Assets directory still remains outside, in the Assets directory.
